"""Initial migration.

Revision ID: eb276366d72a
Revises: 
Create Date: 2022-07-12 23:17:39.014573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb276366d72a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('rendered_data', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.Text(length=90), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('is_bought', sa.Boolean(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=90), nullable=True),
    sa.Column('additional_info', sa.String(length=500), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('item')
    # ### end Alembic commands ###
